### ISSUE TITLE
AGPLv3 or AGPLv3 or any later version?

### ISSUE THREAD

**Issue by donaldr3** [Alovoa/alovoa#1]
It wasn't immediately clear from the repo which versions of the AGPL the work may be used under. Generally that information would be included in license notices in the source files themselves. You can learn how to use GNU licenses and the associated notices at <https://www.gnu.org/licenses/gpl-howto.en.html>. Thanks so much for any clarity you can provide.

**Comment by Nonononoki** [comment]
Hi, thanks for the suggestion.
License notices for every source file is such a bother and too early to include in the current stage. 
All code (except for third-party libraries) is licensed under the AGPLv3 only (because the future is uncertain and there might be drastic changes I might not like), as stated at the bottom of the README.
