### ISSUE TITLE
Registration with GMX and uBlock Origin doesn't work. No confirmation email.

### ISSUE THREAD

**Issue by mruncreative** [Alovoa/alovoa#134]
As the title says. I already wrote you an email some days ago. (to contact@alovoa.com):

I tried registering with uBlock Origin. I got the error {"timestamp":1646868386328,"status":403,"error":"Forbidden","path":"/register"}
I turned off uBlock Origin and it worked. I'm not sure whether it has anything to do with the addon but you should investigate it.
Further I did NOT get a confirmation email and CAN'T request it again. At this point most people would just give up using the site.

https://alovoa.com/imprint doesn't work (or give feedback that the message has been send idk), even with uBlock turned off completely.
I'm using Chromium version 98.

**Comment by Nonononoki** [comment]
https://alovoa.com/imprint works, but I only check once a week. uBlock Origin has nothing to do with the error, you can only access the login and register page a few times per minute for security reasons.
Imprint works, but the feedback didn't work. Fixed with this commit: b9d992ba34e87cd3d1f6371f67bbdb60d210ae6a
GMX and email providers from the same parent company are very picky, but should be working now.
You can activate your account by resetting your password (https://alovoa.com/password/reset), even if you didn't receive your confirmation email address

**Comment by mruncreative** [comment]
Yes, you were right. The email from thursday suddenly appeared in my inbox. I used the password reset link. Nothing happened, so I added admin@alovoa.com to my contact list and only then it appeared in my inbox.
Maybe put a note or something.
