### ISSUE TITLE
Glitch uploaded photos

### ISSUE THREAD

**Issue by zecamigo** [Alovoa/alovoa#171]
On Android, both APP and website.

Uploading photos results in a glitch with vertical lines only.

![Z](https://user-images.githubusercontent.com/7470175/165654212-52677249-2f31-49b8-8581-470715d5f528.jpg)

**Comment by Nonononoki** [comment]
I've seen this issue on a few profiles, but could never reproduce it. Could you upload the original picture?

**Comment by zecamigo** [comment]
> I've seen this issue on a few profiles, but could never reproduce it. Could you upload the original picture?

Unsure if I want to upload my face to github so here it goes. My totally non-AI generated profile photo and the corresponding glitch.

![2Q==](https://user-images.githubusercontent.com/7470175/165870522-ad4de5ad-54c0-4e33-8941-e7ba19774493.jpg)
![944631211](https://user-images.githubusercontent.com/7470175/165870524-36fbe42a-9ed8-4d0a-9ca4-2527b872c672.jpg)

This happens on an Android 11 based custom ROM.
If you want to check my account please provide a private contact method.

**Comment by zecamigo** [comment]
Seems to work with Firefox official, but not with Mull/ mulch webview.
https://gitlab.com/divested-mobile/mulch/

**Comment by Nonononoki** [comment]
"Hardened" browsers are currently unsupported unfortunately. This includes Tor Browser, LibreWolf and Mull. They purposefully block canvas functionality for fingerprinting reasons, but this also means that any legit usage will also be blocked. In this case, it is used to crop images to a specific size, which is very useful because the processing is offloaded to the user. Unless there is a way to detect if the browser has canvas fingerprinting protection enabled with JavaScript (I doubt that) the only workarounds are to either use another browser or to disable `privacy.resistFingerprinting.randomDataOnCanvasExtract` in `about:config`.

**Comment by Nonononoki** [comment]
Nevermind, I think I've created a good solution for this issue: 53ba049e3ae4e8e9ca162a305b38b2c3fc59e24c
Should be working now :)

**Comment by zecamigo** [comment]
Thanks for accommodating that !
