### ISSUE TITLE
User driven verification process

### ISSUE THREAD

**Issue by Nonononoki** [Alovoa/alovoa#191]
Goal: Users can quickly see if the other person is real or not
Concept:
1. User requests to be verified in the /profile page
2. A random verification string of 6 characters will be generated
3. User is prompted to upload an image of them holding a piece of paper with the verification string written on it
4. After uploading the image a verification badge can be seen on the users profile page on search. The badge will have a number next to it.
5. Other users can now click on the badge and see the users profile picture and the verification picture next to each other
6. Then the user will be asked if it's the same person and if the verification text is correct.
7. Yes/No buttons will decide if the badge number will go up or down

**Comment by unbranched** [comment]
I'm a new user and very pleased by this project, but there are very few people and it's already FULL of fakes.
The verification becomes mandatory in my opinion and should be implemented as soon as possible. While this public driven verification is something, it would be also a double edge, with fake people/scammers/idiots selecting "not real" on purpose. It would be better it there were some mods to verify.

There is the same issue in the ability to see the number of blocked and reports on a user profile: I'm new and I have already 1 blocked mark on my profile just because I was talking to a fake and I got him, so he blocked me.
Now people will see MY profile as a warning...

If the verification process will be implemented I think the blocked and reported marks will become useless.

**Comment by Nonononoki** [comment]
Verification feature now implemented! Head to your profile and simply upload your verification picture :)

e70b80ac8d40e0602dc4b327d339ea447f7231bb
370ef50f3264ef63d82e5dce8ae6ddfd595af032
115890404db31680d6913ea7e805886b7dcb5791
b050bd35d39914e0924a6728c12ef059b4532114
000a565defd84358dabef8a25470c7e5a62a36fa
24625b6ec66af1426c3814195efeaa1dc2d6907f
