### ISSUE TITLE
[FEATURE][Feedback needed] Use alovoa-expo as official frontend for the web

### ISSUE THREAD

**Issue by Nonononoki** [Alovoa/alovoa#284]
EDIT: **Feedback needed! Visit [beta.alovoa.com](https://beta.alovoa.com/) to try out the new web frontend!**

No need to maintain 2 separate frontends, as expo/react-native official supports building for the web.

**Comment by Nonononoki** [comment]
Please do not submit or request new GUI features and translations to this repository, but here [alovoa-expo](https://github.com/Alovoa/alovoa-expo) until further notice. This only applies to pages only accessible when logged in.

**Comment by ip6li** [comment]
Is a headless server branch planned? If Alovoa-Expo should be used as only frontend, Alovoa server needs REST frontend, only.

**Comment by Nonononoki** [comment]
@ip6li  No headless only server is planned. Only the user area will be removed. Simple static pages like FAQ, contact, index and the admin area will still be available from the web.

**Comment by ip6li** [comment]
Hmm, I may have a different opinion regarding architecture, because I would consider a more microservice like architecture. My reverse proxy instances in front of my Alovoa instances can redirect static files to static only Nginx instances, which is optimized for caching support by a CDN (e.g. Cloudflare, free edition). Nginx is much faster than a Tomcat based Java solution.

**Comment by Nonononoki** [comment]
New frontend launched for on [beta.alovoa.com](https://beta.alovoa.com/)!

**Comment by Nonononoki** [comment]
Merged PR: 8ff87578121f6dab6cf43ecd2ec842153e6b7fca
