### ISSUE TITLE
[BUG] Properly support E-Mail extensions (Reset password not working)

### ISSUE THREAD

**Issue by natrius** [Alovoa/alovoa#286]
**Describe the bug**

When using an e-mail with e-mail extensions it throws quite some errors. In that case my provider is using `+` as separator, so `email+alovoa@mail.com` for example. This is supported by gmail as well and is an official RFC.

- https://kb.mailbox.org/en/private/e-mail-article/how-to-use-mail-extensions
- https://people.cs.rutgers.edu/~watrous/plus-signs-in-email-addresses.html
- https://en.wikipedia.org/wiki/Email_address#Address_tags
- https://will.koffel.org/post/2014/using-email-plus-addressing/

_Registration_
It 'did' work some time ago 🤷 Haven't tried it again.

_Reset password_
Works

_Change password:_
Just getting `An error occured. Please try again.` without further explanation - i suspect the e-mail extension?
![image](https://github.com/Alovoa/alovoa/assets/7243447/afa1b6de-71d0-45c3-80e7-30742d0935ec)

**To Reproduce**
1. Register an account with e-mail extension
2. Lgout
3. On the login-form press "Forgot password"
4. Enter the E-Mail with extension and open the link to change
5. Enter E-Mail with extension and new password and press "Submit"

**Expected behavior**
New password set.

**Comment by anthonykozar** [comment]
I am having the same problem changing my password after a password reset too but I don't have a + sign in my address or any other unusual characters.  My email domain ends in .net though. 

I  only tried the password reset because I was having tons of failed login attempts,  probably because of the captchas.  They are mostly unreadable so I have to press the button to load a new captcha over and over until I get one that I *think* I can read.  Then I still get a message about incorrect credentials.

So, I thought maybe I mistyped my password when signing up yesterday.  I've tried a couple of different capitalizations but no luck.  I did successfully login to the website once yesterday after three attempts but I logged out and have been unable to log back in again. I am still logged into the Android app however, but I want to use the website since it has more features. 

Does the site prevent login attempts to an account or from a particular IP address after too many failures?

My suggestions:
1. Use two password fields when signing up or changing the password so that users can catch typing mistakes. 
2. Make the captchas more readable!
3. Provide more specific error messages when authentication or password changes fail.  E.g. incorrect password,  incorrect captcha, server error,  etc.

Thanks!

**Comment by anthonykozar** [comment]
Well,  I *was* repeatedly typing my password incorrectly due to differences between my phone's keyboard and my computer's keyboard.  But there would still seem to be something wrong with the password reset function.

**Comment by Nonononoki** [comment]
Passwort reset should now be working again. Thanks for the report!
051d3f5304620f8c5fdaace332fe700f5b6eef42

**Comment by anthonykozar** [comment]
Great!! Thank you! 😊
