### ISSUE TITLE
[FEATURE] More granular options for substance consumption

### ISSUE THREAD

**Issue by Nonononoki** [Alovoa/alovoa#413]
Add more granular selections to "drugs" fields.

Requirements:
- Allow three different options with Yes, No and Sometimes.

Tips:
- Check out UserMiscInfo and UserService.updateUserMiscInfo

**Comment by andresousadotpt** [comment]
I would like to work on this 😀

**Comment by Nonononoki** [comment]
@andresousadotpt Sure, many thanks

**Comment by andresousadotpt** [comment]
Hello @Nonononoki, I took some time to investigate and before committing to a perhaps bad solution or a adequate solution, I found one which would introduce a breaking change (but if we keep the same endpoint until the frontend migrates to the new endpoint this would go smooth).

```
    @PostMapping("/update/misc-info/{infoValue}/{activated}")
    public Set<UserMiscInfo> updateMiscInfo(@PathVariable long infoValue, @PathVariable String activated) throws AlovoaException {
        return userService.updateUserMiscInfo(infoValue, Tools.binaryStringToBoolean(activated));
    }

    @PostMapping("/update/misc-info/{infoValue}/{option}")
    public Set<UserMiscInfo> updateMiscInfoOptions(@PathVariable long infoValue, @PathVariable UserMiscGranularity option) throws AlovoaException {
        return userService.updateUserMiscInfo(infoValue, option);
    }
    
```

Instead of having `activated` we have a option path param. Basically, UserMiscGranularity looks like this:

```
package com.nonononoki.alovoa.entity.user;

public enum UserMiscGranularity {
    YES,
    NO,
    SOMETIMES
}
```

With this we introduce a problem, because if people try to call the API with `SOMETIMES` on a `RELATIONSHIP_SINGLE` value I don't think it would be appropriate. We could have like a lookup table like `Set<MiscValue, EnumMap<UserMiscGranularity>>` and with that we end up not having that issue. (to explain this it is just a "compatibility check table", we check if for that value that came through is indeed compatible with that option, if is not we could default to false\true.)

What do you think so far?

**Comment by Nonononoki** [comment]
@andresousadotpt No need for any breaking changes or enums, simply add more unique database values to UserMiscInfo.java and use the existing endpoint.

```
	@Transient
	public static final long DRUGS_TOBACCO_NO = 31;
	@Transient
	public static final long DRUGS_ALCOHOL_NO = 32;
	@Transient
	public static final long DRUGS_CANNABIS_NO = 33;
	@Transient
	public static final long DRUGS_OTHER_NO = 34;

	@Transient
	public static final long DRUGS_TOBACCO_SOMETIMES = 41;
	@Transient
	public static final long DRUGS_ALCOHOL_SOMETIMES = 42;
	@Transient
	public static final long DRUGS_CANNABIS_SOMETIMES = 43;
	@Transient
	public static final long DRUGS_OTHER_SOMETIMES = 44;
```

updateUserMiscInfo definitely needs to be changed though.

**Comment by andresousadotpt** [comment]
@Nonononoki yeah I though of that, but I thought tha, perhaps, we could have a better way of doing this... But will implement that way for sure!

**Comment by Nonononoki** [comment]
Looks quite good, I also completely forgot about EventListenerConfig. That currently only executes when the table is empty, would it be possible to add it to the existing table?

**Comment by Nonononoki** [comment]
Sorry, I couldn't review your changes because of personal issues. I'll try again next weekend.

**Comment by andresousadotpt** [comment]
No problem, no rush 👍🏼

**Comment by Nonononoki** [comment]
Merged to master
