### ISSUE TITLE
Search by manual location input

### ISSUE THREAD

**Issue by mintedony** [Alovoa/alovoa#54]
Currently search and location are based on HTML5 geolocation. With Firefox, they base it on nearby WiFi Connections and your IP, both of which reduce your privacy. The data is sent to Google Location Services as well, again lessening privacy. I don't know what Chromium browsers do.

Additionally, IP based location definition is sometimes inaccurate because ISPs could report their location from a headquarters, or another country entirely.

It would be nice to see the option to input a general town and country, and search based on that. Right now I get "No Users Found" and I'm not sure if it's because my location was polled wrong, or if there's just nobody signed up near me :laughing: 

Cheers to Release 1.0!

**Comment by Nonononoki** [comment]
Are you talking about the desktop browser? Because HTML Geolocation is using GPS on mobile imho. 
It's less accurate on desktop, so I don't think Google having the location of your ISP would be a problem. Implementing manual input sounds like a lot of work, especially for towns, because there are many of them and many town even have the same name :)

There are not many users yet, so it's definitely possible to not find users near you. I'm about to change that with ad campaigns, but preparation takes time.

Leaving this issue open for debate.

**Comment by zen0bit** [comment]
Choose per countries could be enough..

**Comment by Nonononoki** [comment]
This also means that all users have to manually set the country they are residing, not very elegant. I'm down for choosing a location on a map, like in this library https://leafletjs.com/examples/quick-start/
Not a priority right now, but will implement is faster if more users request the feature, or someone else can create a pull request.

**Comment by Nonononoki** [comment]
@zen0bit
I now included a manual way to pick your location manually. Just turn off your GPS or disable the location permission to pick your location on a map. Have fun :)

**Comment by derMart** [comment]
@Nonononoki That would be awesome! Sadly, I havent figured out how to manually pick the location. Speaking of the "official" ? domain alovoa.com.

The webapp does not even request geolocation permissions. It just seems to base the location of by IP address, which may be pretty far off (not even same country). How to pick the location in the webapp?

Same for the f-droid android app. There location permission was asked for and I denied. Still, haven't found any way to get a map / pick a location. How to get there in the android app?

best
