### ISSUE TITLE
Service emails should come from same domain as host

### ISSUE THREAD

**Issue by mintedony** [Alovoa/alovoa#55]
Right now activation, reset, and notification emails for https://alovoa.com/ come from a gmail.com email address. It would look nicer to come from alovoa.com or a non-privacy invasive provider :smiley: 
Cheers!

**Comment by Nonononoki** [comment]
Yes, this is the plan. I already have everything set up. The problem is that my hosting provider blocks all ports for emails to prevent spam. They have to policy of opening ports until the first bill arrives, so I have to wait.

https://docs.hetzner.com/cloud/servers/faq/#why-can-i-not-send-any-mails-from-my-server

**Comment by Nonononoki** [comment]
Local mailserver has now been setup and working properly! :)
