### ISSUE TITLE
Minimum REQUIRED age on Alovoa should be 18

### ISSUE THREAD

**Issue by mintedony** [Alovoa/alovoa#56]
I just noticed this in the Terms of Service
> 2. Eligibility
you are at least 16 years old.

When signing up, the default Date of Birth is set for the current date, 2005... 16 years ago.

Why is the minimum age **for a dating site** set to 16 years old? That seems quite inappropriate and sends a bad message about the service to start with...

The minimum age should be set to 18 in the code-base as that is normally defined as the initial "adult" age in the majority of countries worldwide. This should be changed in the ToS and in the signup process.

I am having difficulty finding the hardcoded definitions for the date of birth and ToS information page however.

**Comment by Nonononoki** [comment]
Minimum age can be found in the ToS under point 2: you are at least 16 years old.
I had some debate with a few people over this. 
My points are:
- The age of consent for **sex** is in a few states/countries 18. It's even 16 in the majority of US states (34). This is not a sex platform.
- The platform protects minors from adults, they cannot find other in search nor can they match or communicate with each other on the platform.
- I'm residing in Germany, and there are dating platform with the same minimum age.

Leaving this issue open for debate.

**Comment by HorseJump** [comment]
Here is some feedback you may find worthwhile: https://lemmy.ml/post/69260

**Comment by Lenny3D** [comment]
You could just set up another instance for residents of the USA or set the minimum age based on location. In my opinion, organisations and services EU should not bow down to the USA's prudish standards on their own soil. 

Because of this prudishness in the USA, some innocent videos on YouTube are blocked in the EU for people without a Google, like this sketch from Monty Python: https://www.youtube.com/watch?v=yYMRjnM6j6w. Why? Because at one point, there is a painting of a naked women in view for 3 seconds? [sarcasm]Yes, this is seriously hardcore pornographic material. This will scar a six year old for life, because at that point they will never have seen a naked woman in their life. Not even their own mother. [/sarcasm] And this is only a tiny part of the USA's ridiculously prudish standards that affects us, Europeans.

No, we of the USA don't do sex. Sex is the ultimate evil. We should teach children that humans procreate with war instead. War is glorious and our children should know that. Make war, not love. 

I knew that sex was a thing since I was twelve. Since schools actually teach over here teach children actually such things instead of treating is as a taboo. Did we laugh at schematic drawings of penises and vaginas? Yes. Did we lose our innocence? Maybe. Did we learn that mutual consent is essential, unsafe sex can lead to pregnancy and STDs, and how our bodies change during puberty? Absolutely!

Please, keep this service to European standards for European users.

**Comment by cristiancahe** [comment]
16 as a minimum age for a dating platform it's just not okay. When I signed up and saw this it didn't feel right.
In the majority of countries 18 is the minimum legal age and that should be taken into consideration, not whether 16 is an age of consent or there are other platforms that are open for minors.
I agree with this issue. Minimum age should be raised to 18.

**Comment by Nonononoki** [comment]
Because this is not a technical issue it's moving to discussions: https://github.com/Alovoa/alovoa/discussions/102
