### ISSUE TITLE
more attention

### ISSUE THREAD

**Issue by zen0bit** [Alovoa/alovoa#76]
I wanna more eyes on this great project and hopefully, more developers to push changes...
saw you already put on reddit
so
I post about alovoa on [lemmy](https://lemmy.ml/post/70846)
reddit opensource alternative

**Comment by Nonononoki** [comment]
I'll start an ad campaign when the mail server actually works (first in Germany).
Not sure what else I can do alone tho.

**Comment by wiki-me** [comment]
I can post to reddit/tildes/friendica once you think it is ready to get a little more attention.

I think just blogging (say once a year, or maybe every 3 or 6 months) could be good because it wil give people something to post on social media or report on a few FOSS or software websites (stuff like new features you imlemented, growth in usage , fundraisers etc).

You could experiment and measure what impact different promotion methods have, using stuff like [star track](https://seladb.github.io/StarTrack-js/#/) to see if there is a spide in the number of stars, or maybe develop your own metrics for this (number of new sign ups ? monthly active users? page views?). you could report active users to [the-federation.info](https://the-federation.info/) (which could also give the project a little more exposure).

**Comment by Nonononoki** [comment]
Closing this issue because it's not a technical one. Feel free to start a topic in discussions: https://github.com/Alovoa/alovoa/discussions
