### ISSUE TITLE
Add referral system

### ISSUE THREAD

**Issue by Nonononoki** [Alovoa/alovoa#88]
Idea:
+ Add referral code input in register and register-oauth
+ Add referal code in profile

Upon each successful registration get a small amount added to their "wallet" (it's just a number, bragging rights only), suggested amount is 0.50€ so it won't discredit the people who donate to keep the platform alive.
Limit the amount of referrals, suggested amount is 20.

**Comment by wiki-me** [comment]
So it should have the currency unit of euro ( € ) when showing the number?

This seems confusing.

**Comment by Nonononoki** [comment]
@wiki-me Well, the donation amount is already present and in euros. Not sure what's confusing.

**Comment by wiki-me** [comment]
Maybe i misunderstood you, but is it not real money?, Won't someone think that maybe if it's in units of currency he can withdraw the money? (and then start looking for a way for a long time to do it possibly confusing him), it's not a far fetch scerario because some alternative social media platforms pay creators (steemit and minds for example).

**Comment by Nonononoki** [comment]
It's not real money that they can use, that's true. And I wouldn't tell the users anything amount money at all, just that their visibility may get boosted slightly.

**Comment by Nonononoki** [comment]
67317b80d729c6139a9bbe2b34bf02925a597c68
a3e137739e51337a7da9c16436cbf0e59752e5b0
3dbdeae9cdf0b08b1ba9dd2ab126af43b1a13a4d
9629539f4f2d6b7ea6ded9ed5196582da1aa2c90
