### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by Sweazou** [Alovoa/alovoa#92]
I can't log in on Pixel 5, i tried severals times and i'm pretty sure the captcha and the passwords are correct.
![Screenshot_20210722-231640.png](https://user-images.githubusercontent.com/50371041/126733811-8a01cf39-5cba-4d36-a095-533939b00b90.png)
And when i tried to reset the password just to be sure it's not me i got an error.
![Screenshot_20210722-231947.png](https://user-images.githubusercontent.com/50371041/126733995-98764d49-9731-44de-bc1d-0d9060bb5008.png)

**Comment by Nonononoki** [comment]
@Sweazou Not many people speak French, please change the language to English when submitting a bug.

This can occur when there's data corruption, because the email address is encrypted and something went wrong when saving the encrypted value. This problem should be fixed in a recent update, about 2 days ago.
To verify it please create a new account with the same email address.
If you have logged in or created the account less than 2 days ago please contact me via email: contact@alovoa.com

**Comment by Nonononoki** [comment]
Closing issue because reporter is not responding
